apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-api
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-api
  template:
    metadata:
      labels:
        app: upload-api
    spec:
      imagePullSecrets:
        - name: registry-auth-secret  
      containers:
        - name: upload-api
          image: 10.0.2.84:32002/upload_api
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: b2b-prod-secret  

---
apiVersion: v1
kind: Service
metadata:
  name: upload-api-service
  namespace: registry  
spec:
  type: NodePort
  ports:
    - port: 8000  
      targetPort: 8000  
      nodePort: 32008  
  selector:
    app: upload-api

